version: 2

updates:

  - package-ecosystem: "pip"
    directory: "/"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "Task"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
