dist: xenial
language: python


branches:
  only:
    - master


jobs:
  include:
    - python: 3.7
      env: TOXENV=flake8

    - python: 3.7
      env: TOXENV=mypy

    - python: 3.6
      env: TOXENV=coverage-py37,codecov

    - python: 3.6
      env: TOXENV=coverage-py36,codecov


env:
  - TOX_SKIP_MISSING_INTERPRETERS=False


install:
  - pip install tox


script:
  - tox


notifications:
  email:
    recipients:
      - ranger-tech-list@burningman.org
